version: "3.8"
services:
  jekyll:
    build:
      context: .
    volumes:
      - ./jekyll:/srv/jekyll
    ports:
      - "4000:4000"
    command: jekyll serve --watch --force_polling --host 0.0.0.0
