version: "3.8"
services:
  jekyll:
    build:
      context: .
    volumes:
      - ./jekyll:/srv/jekyll
    ports:
      - "4000:4000"
    command: jekyll build
  nginx:
    image: nginx:latest
    depends_on:
      - jekyll
    ports: 
      - 8089:80
    volumes:
      - ./jekyll/_site/:/usr/share/nginx/html

