services:
  # Build and hot reload (-w) static Markdown files in the .posts/ directory
  jekyll-prod:
    build:
      context: .
    volumes:
      - ./jekyll:/srv/jekyll
    ports:
      - "4000:4000"
    command: "bundle exec jekyll build -w"
    profiles:
      - prod
    restart: unless-stopped
  # Host the files of the site on port 8089
  nginx:
    image: docker.io/library/nginx:1.27.4-alpine
    depends_on:
      - jekyll-prod
    ports:
      - 8089:80
    volumes:
      - ./jekyll/_site/:/usr/share/nginx/html
    profiles:
      - prod
    restart: unless-stopped
  nginx-exporter:
    image: docker.io/nginx/nginx-prometheus-exporter:1.4.0
    depends_on:
      - nginx
    ports:
      - 9113:9113
    profiles:
      - prod
    restart: unless-stopped
  # Hook nginx exposed port onto the web
  cloudflared:
    image: docker.io/cloudflare/cloudflared:2025.2.0
    depends_on:
      - nginx
    profiles:
      - prod
    restart: unless-stopped
    command: "tunnel --no-autoupdate run --token ${TUNNEL_TOKEN} --url 'http://localhost:8089'"
    env_file:
      - .env
    network_mode: "host" # Ensures it can connect to services on localhost
  jekyll-dev:
    build:
      context: .
    volumes:
      - ./jekyll:/srv/jekyll
    ports:
      - "4000:4000"
    command: "bundle exec jekyll serve --watch --force_polling --host 0.0.0.0"
    profiles:
      - dev
